apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  FRONTEND_PERSONS_API: "http://localhost:30002/api/persons/"
  FRONTEND_CONNECTIONS_API: "http://localhost:30001/api/persons/"
metadata:
  name: db-env